spring.config.import=optional:file:./env.properties
spring.application.name=ecomm

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiry=${JWT_ACCESS_EXPIRY}
jwt.refresh-expiry=${JWT_REFRESH_EXPIRY}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Cookie
app.cookie.secure=${COOKIE_SECURE}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Spring Security OAuth2 (Firebase token verification)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/${FIREBASE_PROJECT_ID}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
